.TH "cellule" 3 "Sun Mar 16 2014" "DPLL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cellule \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <structures\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBval\fP"
.br
.RI "\fIvaleur correspondant a une arrete ou une clause \fP"
.ti -1c
.RI "struct \fBcellule\fP * \fBnext\fP"
.br
.RI "\fIpointeur vers la valeur suivante \fP"
.ti -1c
.RI "struct \fBcellule\fP * \fBprev\fP"
.br
.RI "\fIpointeur vers la valeur precedente \fP"
.ti -1c
.RI "\fBType_elt\fP \fBelement\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBType_elt\fP element"

.SS "struct \fBcellule\fP* next"

.PP
pointeur vers la valeur suivante 
.SS "struct \fBcellule\fP* prev"

.PP
pointeur vers la valeur precedente 
.SS "int val"

.PP
valeur correspondant a une arrete ou une clause 

.SH "Author"
.PP 
Generated automatically by Doxygen for DPLL from the source code\&.
