.TH "src/main.c" 3 "Sun Mar 16 2014" "DPLL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include '\&.\&./head/const\&.h'\fP
.br
\fC#include '\&.\&./head/structures\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtests\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (intargc, char *argv[])"

.SS "void tests ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for DPLL from the source code\&.
